version: 2

jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version
          command: |
            rustup --version
            rustc --version
            cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test

workflows:
  version: 2
  workflow:
    jobs:
      - test
