version: 2

jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Show version information
          command: |
            rustup --version
            rustc --version
            cargo --version
      - run:
          name: Install dependencies
          command: rustup component add rustfmt
      - run:
          name: Format
          command: cargo rustfmt -- --check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test

workflows:
  version: 2
  workflow:
    jobs:
      - test
