version: 2

jobs:
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Save rustup version
          command: rustup --version > ~/.rustup-version
      - restore_cache:
          keys:
            - rustup-{{ checksum "~/.rustup-version" }}
      - run:
          name: Install dependencies
          command: rustup component add rustfmt clippy
      - save_cache:
          key: rustup-{{ checksum "~/.rustup-version" }}
          paths:
            - /usr/local/rustup
      - run:
          name: Format
          command: cargo fmt -- --check
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build
      - save_cache:
          key: cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
      - run:
          name: Check
          command: cargo clippy --all-targets --all-features -- -D warinigs
      - run:
          name: Test
          command: cargo test

workflows:
  version: 2
  workflow:
    jobs:
      - test
