version: 2

jobs:
  test:
    docker:
      - image: rust:1.33.0-stretch
    steps:
      - checkout
      - run:
          name: Save rustup version
          command: rustup --version | tee ~/.rustup-version
      - run:
          name: Save rustc version
          command: rustc --version | tee ~/.rustc-version
      - restore_cache:
          keys:
            - rustup-{{ checksum "~/.rustup-version" }}
      - run:
          name: Install dependencies
          command: rustup component add rustfmt clippy
      - save_cache:
          key: rustup-{{ checksum "~/.rustup-version" }}
          paths:
            - /usr/local/rustup
      - run:
          name: Format
          command: cargo fmt -- --check
      - run:
          name: Generate a lockfile
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-lock-{{ checksum "~/.rustc-version" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build
      - save_cache:
          key: cargo-lock-{{ checksum "~/.rustc-version" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
      - run:
          name: Check
          command: cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: Test
          command: cargo test

workflows:
  version: 2
  workflow:
    jobs:
      - test
